
'use strict';
const APP_VERSION='3.0.0';
const STORAGE_KEY='oralHygieneStudyApp_v3';
const LEGACY_KEYS=['oralHygieneStudyApp_v2','oralHygieneStudyApp_v1','oralHygieneStudyApp','oralHygieneStudyProgressV2','oralHygieneStudyProgressV1','oralHygiene491_v1'];
const QUESTIONS=JSON.parse(document.getElementById('questionData').textContent);
const $=id=>document.getElementById(id);
const validIds=new Set(QUESTIONS.map(q=>Number(q.id)));
const categoryNames=[...new Map(QUESTIONS.map(q=>[q.category,q.sectionNumber])).entries()].sort((a,b)=>a[1]-b[1]).map(x=>x[0]);
const memoryStore=new Map();
let persistence={type:'memory',available:false};
let filtered=[];let cursor=0;let answerVisible=false;let figuresOpen=false;let deferredPrompt=null;let searchTimer=null;let toastTimer=null;

function detectStorage(){for(const type of ['localStorage','sessionStorage']){try{const s=window[type],k='__oral_hygiene_test__';s.setItem(k,'1');s.removeItem(k);persistence={type,available:true};return s}catch(_e){}}return{getItem:k=>memoryStore.get(k)??null,setItem:(k,v)=>memoryStore.set(k,String(v)),removeItem:k=>memoryStore.delete(k)}}
const store=detectStorage();
function defaultState(){return{unknownIds:[],reviewedIds:[],lastQuestionId:1,mode:'all',category:'all',order:'number',search:'',shuffledIds:[],theme:'system',updatedAt:null}}
function safeParse(s){try{return JSON.parse(s)}catch(_e){return null}}
function readStored(){let raw=null;try{raw=store.getItem(STORAGE_KEY)}catch(_e){}if(!raw){for(const k of LEGACY_KEYS){try{const old=store.getItem(k);if(old){raw=old;store.setItem(STORAGE_KEY,old);break}}catch(_e){}}}return safeParse(raw)||{}}
function sanitizeState(value){const out=Object.assign(defaultState(),value&&typeof value==='object'?value:{});out.unknownIds=[...new Set((Array.isArray(out.unknownIds)?out.unknownIds:[]).map(Number).filter(id=>validIds.has(id)))].sort((a,b)=>a-b);out.reviewedIds=[...new Set((Array.isArray(out.reviewedIds)?out.reviewedIds:[]).map(Number).filter(id=>validIds.has(id)))].sort((a,b)=>a-b);out.shuffledIds=[...new Set((Array.isArray(out.shuffledIds)?out.shuffledIds:[]).map(Number).filter(id=>validIds.has(id)))];out.mode=['all','unlearned','unknown','known'].includes(out.mode)?out.mode:'all';out.order=['number','shuffle'].includes(out.order)?out.order:'number';out.category=(out.category==='all'||categoryNames.includes(out.category))?out.category:'all';out.search=typeof out.search==='string'?out.search:'';out.theme=['system','light','dark'].includes(out.theme)?out.theme:'system';out.lastQuestionId=validIds.has(Number(out.lastQuestionId))?Number(out.lastQuestionId):1;out.updatedAt=typeof out.updatedAt==='string'?out.updatedAt:null;return out}
const state=sanitizeState(readStored());

function persist(message=''){state.updatedAt=new Date().toISOString();let ok=false;try{store.setItem(STORAGE_KEY,JSON.stringify(state));ok=true}catch(_e){}updateStorageNotice(ok);updateStats();if(message)toast(message);return ok}
function updateStorageNotice(ok=persistence.available){const pill=$('savedAt'),notice=$('storageNotice');if(persistence.type==='localStorage'&&ok){pill.textContent=state.updatedAt?`自動保存 ${new Date(state.updatedAt).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`:'自動保存ON';pill.classList.remove('warn');notice.hidden=true}else if(persistence.type==='sessionStorage'&&ok){pill.textContent='このタブ内で保存';pill.classList.add('warn');notice.textContent='この環境では長期保存が制限されています。GitHub Pagesの公開URLをSafariで開くと保存できます。';notice.hidden=false}else{pill.textContent='一時保存のみ';pill.classList.add('warn');notice.textContent='端末保存が利用できないため、この表示中だけ記録します。';notice.hidden=false}}
function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function shuffleArray(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function currentQuestion(){return filtered[cursor]||null}
function buildFiltered(){const reviewed=new Set(state.reviewedIds),unknown=new Set(state.unknownIds);const term=state.search.trim().toLowerCase();let list=QUESTIONS.filter(q=>{if(state.category!=='all'&&q.category!==state.category)return false;if(state.mode==='unlearned'&&reviewed.has(q.id))return false;if(state.mode==='unknown'&&!unknown.has(q.id))return false;if(state.mode==='known'&&(!reviewed.has(q.id)||unknown.has(q.id)))return false;if(term){const hay=`${q.id} ${q.category} ${q.question} ${q.answer} ${q.note||''}`.toLowerCase();if(!hay.includes(term))return false}return true});if(state.order==='shuffle'){const ids=list.map(q=>q.id);const currentSet=new Set(ids);let order=state.shuffledIds.filter(id=>currentSet.has(id));for(const id of ids)if(!order.includes(id))order.push(id);if(order.length!==ids.length||!state.shuffledIds.length)order=shuffleArray(ids);state.shuffledIds=order;const rank=new Map(order.map((id,i)=>[id,i]));list.sort((a,b)=>rank.get(a.id)-rank.get(b.id))}else list.sort((a,b)=>a.id-b.id);return list}
function refreshFiltered(preferStored=true){const oldId=currentQuestion()?.id;filtered=buildFiltered();let target=preferStored?state.lastQuestionId:oldId;if(!target||!filtered.some(q=>q.id===target))target=filtered[0]?.id;cursor=Math.max(0,filtered.findIndex(q=>q.id===target));render();persist('')}
function updateStats(){const reviewed=new Set(state.reviewedIds),unknown=new Set(state.unknownIds);const known=[...reviewed].filter(id=>!unknown.has(id));$('totalCount').textContent=QUESTIONS.length;$('reviewedCount').textContent=reviewed.size;$('unknownCount').textContent=unknown.size;$('knownCount').textContent=known.length;const pct=Math.round(reviewed.size/QUESTIONS.length*100);$('progressBar').style.width=`${pct}%`;$('progressLabel').textContent=`学習済み ${pct}%`;$('filterCount').textContent=`${filtered.length}問を表示`}
function closeFigures(){figuresOpen=false;$('figureBody').hidden=true;$('toggleFigures').setAttribute('aria-expanded','false');$('figureToggleLabel').textContent='図・表を表示'}
function openFigures(){const q=currentQuestion();if(!q||!q.figures?.length)return;figuresOpen=true;$('figureBody').hidden=false;$('toggleFigures').setAttribute('aria-expanded','true');$('figureToggleLabel').textContent='図・表を閉じる';renderFigureList(q)}
function toggleFigures(){figuresOpen?closeFigures():openFigures()}
function renderFigureList(q){const list=$('figureList');list.replaceChildren();for(const fig of q.figures||[]){const figure=document.createElement('figure');figure.className='figure-card';const btn=document.createElement('button');btn.type='button';btn.setAttribute('aria-label','図表を拡大');const img=document.createElement('img');img.src=fig.src;img.alt=fig.caption||'問題の図表';img.loading='eager';img.addEventListener('error',()=>{const msg=document.createElement('div');msg.className='figure-error';msg.textContent=`画像を読み込めません：${fig.src}`;btn.replaceWith(msg)});btn.appendChild(img);btn.addEventListener('click',()=>openDialog(fig));figure.appendChild(btn);if(fig.caption){const cap=document.createElement('figcaption');cap.textContent=fig.caption;figure.appendChild(cap)}list.appendChild(figure)}}
function openDialog(fig){$('dialogImage').src=fig.src;$('dialogCaption').textContent=fig.caption||'';const d=$('imageDialog');if(typeof d.showModal==='function')d.showModal()}
function closeDialog(){const d=$('imageDialog');if(d.open)d.close()}
function render(){updateStats();const q=currentQuestion();const has=q!==null;$('studyCard').hidden=!has;$('emptyCard').hidden=has;$('prevButton').disabled=!has||cursor<=0;$('nextButton').disabled=!has||cursor>=filtered.length-1;if(!has){$('position').textContent='0 / 0';$('stickyPosition').textContent='問—';return}state.lastQuestionId=q.id;answerVisible=false;$('answerArea').hidden=true;$('revealWrap').hidden=false;closeFigures();const hasFigures=Array.isArray(q.figures)&&q.figures.length>0;$('figurePanel').hidden=!hasFigures;$('toggleFigures').disabled=!hasFigures;$('figureList').replaceChildren();$('questionText').textContent=q.question;$('answerText').textContent=q.answer;$('questionNumber').textContent=`問${q.id} / ${QUESTIONS.length}`;$('position').textContent=`${cursor+1} / ${filtered.length}`;$('stickyPosition').textContent=`問${q.id}`;$('badges').replaceChildren();const b1=document.createElement('span');b1.className='badge';b1.textContent=q.category;$('badges').appendChild(b1);const reviewed=state.reviewedIds.includes(q.id),unknown=state.unknownIds.includes(q.id);if(reviewed){const b=document.createElement('span');b.className=`badge ${unknown?'status-unknown':'status-known'}`;b.textContent=unknown?'分からない':'わかった';$('badges').appendChild(b)}history.replaceState(null,'',`${location.pathname}${location.search}#q=${q.id}`);persist('')}
function reveal(){if(!currentQuestion())return;answerVisible=true;$('answerArea').hidden=false;$('revealWrap').hidden=true;$('answerArea').scrollIntoView({behavior:'smooth',block:'nearest'})}
function mark(unknown){const q=currentQuestion();if(!q)return;const reviewed=new Set(state.reviewedIds),bad=new Set(state.unknownIds);reviewed.add(q.id);unknown?bad.add(q.id):bad.delete(q.id);state.reviewedIds=[...reviewed].sort((a,b)=>a-b);state.unknownIds=[...bad].sort((a,b)=>a-b);persist(unknown?'「分からない」に保存しました':'「わかった」に保存しました');render()}
function move(delta){const next=cursor+delta;if(next<0||next>=filtered.length)return;cursor=next;render();$('studyCard').scrollIntoView({behavior:'smooth',block:'start'})}
function jumpToQuestion(raw){const id=Number(raw);if(!Number.isInteger(id)||!validIds.has(id)){toast('1〜491の問題番号を入力してください');$('jumpInput').focus();return}let idx=filtered.findIndex(q=>q.id===id);if(idx<0){state.mode='all';state.category='all';state.order='number';state.search='';state.shuffledIds=[];$('mode').value='all';$('category').value='all';$('order').value='number';$('search').value='';filtered=buildFiltered();idx=filtered.findIndex(q=>q.id===id);toast(`絞り込みを解除して問${id}へ移動しました`)}else toast(`問${id}へ移動しました`);cursor=idx;state.lastQuestionId=id;$('jumpInput').value='';render();persist('');$('studyCard').scrollIntoView({behavior:'smooth',block:'start'})}
function setControl(key,value){state[key]=value;if(key==='order'&&value==='shuffle')state.shuffledIds=[];persist('設定を保存しました');refreshFiltered(false)}
function clearSearch(){$('search').value='';state.search='';persist('検索を解除しました');refreshFiltered(false)}
function reshuffle(){state.shuffledIds=[];refreshFiltered(false);persist('並びをシャッフルしました')}
function exportData(){const payload={app:'口腔衛生学暗記アプリ',version:APP_VERSION,exportedAt:new Date().toISOString(),state:sanitizeState(state)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`口腔衛生学_学習データ_${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('バックアップを書き出しました')}
function importData(input){const file=input.files&&input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));Object.assign(state,sanitizeState(data.state||data));syncControls();persist('バックアップを読み込みました');refreshFiltered(true)}catch(_e){alert('このファイルは読み込めませんでした。')}finally{input.value=''}};reader.readAsText(file)}
function resetUnknown(){if(!confirm('「分からなかった」の記録をすべて消しますか？'))return;state.unknownIds=[];persist('復習対象をリセットしました');refreshFiltered(false)}
function resetAll(){if(!confirm('学習状況と設定をすべて初期化しますか？\nこの操作は元に戻せません。'))return;Object.assign(state,defaultState());try{store.removeItem(STORAGE_KEY);for(const k of LEGACY_KEYS)store.removeItem(k)}catch(_e){}syncControls();refreshFiltered(false);toast('すべて初期化しました')}
function syncControls(){$('mode').value=state.mode;$('category').value=state.category;$('order').value=state.order;$('search').value=state.search;$('theme').value=state.theme;document.documentElement.dataset.theme=state.theme}
function initControls(){for(const name of categoryNames){const o=document.createElement('option');o.value=name;o.textContent=name;$('category').appendChild(o)}syncControls()}
function bind(){
 $('toggleFigures').addEventListener('click',toggleFigures);$('revealButton').addEventListener('click',reveal);$('knownButton').addEventListener('click',()=>mark(false));$('unknownButton').addEventListener('click',()=>mark(true));$('prevButton').addEventListener('click',()=>move(-1));$('nextButton').addEventListener('click',()=>move(1));
 $('jumpButton').addEventListener('click',()=>jumpToQuestion($('jumpInput').value));$('jumpInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();jumpToQuestion(e.currentTarget.value)}});$('stickyPosition').addEventListener('click',()=>{$('jumpInput').focus();$('jumpInput').scrollIntoView({behavior:'smooth',block:'center'})});
 $('mode').addEventListener('change',e=>setControl('mode',e.target.value));$('category').addEventListener('change',e=>setControl('category',e.target.value));$('order').addEventListener('change',e=>setControl('order',e.target.value));$('theme').addEventListener('change',e=>{state.theme=e.target.value;document.documentElement.dataset.theme=state.theme;persist('表示テーマを変更しました')});
 $('search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.search=e.target.value;persist('');refreshFiltered(false)},180)});$('clearSearch').addEventListener('click',clearSearch);$('reshuffle').addEventListener('click',reshuffle);$('showAllButton').addEventListener('click',()=>{state.mode='all';state.category='all';state.search='';syncControls();refreshFiltered(false)});
 $('exportButton').addEventListener('click',exportData);$('importFile').addEventListener('change',e=>importData(e.target));$('resetUnknownButton').addEventListener('click',resetUnknown);$('resetAllButton').addEventListener('click',resetAll);$('closeDialog').addEventListener('click',closeDialog);$('imageDialog').addEventListener('click',e=>{if(e.target===$('imageDialog'))closeDialog()});
 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key===' '&&!answerVisible){e.preventDefault();reveal()}if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(answerVisible&&e.key.toLowerCase()==='w')mark(false);if(answerVisible&&e.key.toLowerCase()==='x')mark(true);if(e.key.toLowerCase()==='f')toggleFigures()});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').hidden=false});$('installButton').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installButton').hidden=true});
}
function fatal(error){console.error(error);const el=$('fatal');el.hidden=false;el.textContent=`アプリの読み込みに失敗しました。\n${error?.message||String(error)}`;$('app').hidden=true}
function init(){try{if(!Array.isArray(QUESTIONS)||QUESTIONS.length!==491)throw new Error('問題データ数が正しくありません');initControls();bind();updateStorageNotice();const hashId=Number((location.hash.match(/q=(\d+)/)||[])[1]);if(validIds.has(hashId))state.lastQuestionId=hashId;refreshFiltered(true);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(console.warn)}catch(e){fatal(e)}}
init();
